### PR TITLE
Add gson-2.6.2 to lib/

### PR DESCRIPTION
**Pull request by Dominator008**
This is done in preparation for updating Closure Compiler to v20160315.

### CODE REVIEW

**Comment by Dominator008** [comment]
@rluble

**Comment by tbroyer** [comment]
Do we really need to jarjar gson?

**Comment by Dominator008** [comment]
@tbroyer My guess is no since Gson is mostly GWT-incompatible. But should we do it for consistency?

**Comment by rluble** [comment]
I think we could use gson unrebased like ASM. The main reason to jarjar is to make sure that the compiler is hermetic and can work in environments where there are other (incompatible) versions of the library. I don't think GSON will need jarjared. AFAICT gson does not change much and its apis are always backward compatible.

**Comment by Dominator008** [comment]
OK I've removed the rebasing.

**Pull request merged**
