### PR TITLE
Added a minimal ant zipscanner jar

### PR DESCRIPTION
**Pull request by niloc132**

### CODE REVIEW

**Comment by niloc132** [comment]
Probably the readme should be moved up one directory, any  other thoughts on versioning, where this goes in the general directory structure?

**Comment by tbroyer** [comment]
Actually, reading that readme, given that the code had to be changed from the original Ant code, I'd rather have the source files directly in GWT's dev/core/src.

Either that or maybe adding a `*.patch` here rather than referencing a third-party repository (see how it's done for streamhtmlparser, although not exactly the same situation).

BTW, given that we already have ant-1.6.5.jar, do you think we could prune enough code with just JarJar and a `keep **.ZipScanner`? It would likely include a bit more classes than you have, but maybe it'd be enough?

**Comment by tbroyer** [comment]
OK, just tried out with JarJar:
```
rule org.apache.tools.** com.google.gwt.thirdparty.apache.@1
keep **.ZipScanner
```
and
```
java -jar lib/tonicsystems/jarjar-1.0rc8.jar process lib/apache/ant-1.6.5.jarjar lib/apache/ant-1.6.5.jar lib/apache/ant-zipscanner-1.6.5.jar
```
and it leaves 292 files (from the 612 files in the original class), with a file size down to 436KiB (from 991KiB).

Now, that's non negligible unnecessary code left, but enough to remove our dependency on Ant. The gwt-dev.jar from the ZIP distribution would be a bit smaller, whereas the one in Maven a bit bigger but without the dependency on Ant (so, yes, you'd download 436KiB more each time there's a new version of GWT).

An approach with a patch would work as follow (untested):
 1. unzip `lib/apache/ant-1.6.5-src.jar`
 2. apply the `lib/apache/ant-zipscanner-1.6.5.patch`
 3. run the following to compile the classes and package the JAR
   ```
   javac -implicit:class -sourcepath . org/apache/tools/ant/types/ZipScanner.java
   jar -Mcvf ant-zipscanner-1.6.5.jar $(find . -name '*.class')
   ```
   (include `--release 8` in the `javac` command if using JDK 9+, otherwise use a JDK 8, and no need to even pass `-target 1.8`)

**Comment by niloc132** [comment]
My concern in merely jarjaring is that while we "remove the dependency", we risk not removing the dangerous APIs that raise those red flags - at the end of the day, the important part is that we reduce the API surface area, not the size of the jar.

I'll script up what you describe and make a new pull request - should not take long, since the patch effectively already exists in the form of git history in the linked repo. 

Thanks for the feedback.

**Pull request closed without merging**
